### ISSUE TITLE
Error when compile img4tool

### ISSUE THREAD

**Issue by vostai** [tihmstar/img4tool#11]
Hi guys, please help me out. I'm trying to compile img4tool. I don't know how to install it dependences, so when I `make` I have error, please check it out

> make  all-recursive
make[1]: Entering directory '/home/admin1/Downloads/img4tool-master'
Making all in img4tool
make[2]: Entering directory '/home/admin1/Downloads/img4tool-master/img4tool'
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -g -O2 -std=c11 -D IMG4TOOL_VERSION_COMMIT_COUNT=\"\" -D IMG4TOOL_VERSION_COMMIT_SHA=\"\" -MT img4tool-img4tool.o -MD -MP -MF .deps/img4tool-img4tool.Tpo -c -o img4tool-img4tool.o `test -f 'img4tool.c' || echo './'`img4tool.c
img4tool.c: In function ‘im4mFormShshFile’:
img4tool.c:41:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(buf, fSize, 1, f);
     ^
img4tool.c: In function ‘readFromFile’:
img4tool.c:78:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     if (ret) fread(ret, size, 1, f);
              ^
img4tool.c: In function ‘readPlistFromFile’:
img4tool.c:95:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(buf, size, 1, f);
     ^
img4tool.c: In function ‘main’:
img4tool.c:362:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         if (buf) fread(buf, size, 1, f);
                  ^
img4tool.c:406:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         if (buf) fread(buf, size, 1, im4m);
                  ^
mv -f .deps/img4tool-img4tool.Tpo .deps/img4tool-img4tool.Po
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -g -O2 -std=c11 -D IMG4TOOL_VERSION_COMMIT_COUNT=\"\" -D IMG4TOOL_VERSION_COMMIT_SHA=\"\" -MT img4tool-img4.o -MD -MP -MF .deps/img4tool-img4.Tpo -c -o img4tool-img4.o `test -f 'img4.c' || echo './'`img4.c
img4.c: In function ‘asn1ElementAtIndexWithCounter’:
img4.c:93:2: warning: #warning TODO add lenght and range checks [-Wcpp]
 #warning TODO add lenght and range checks
  ^
img4.c: In function ‘asn1PrintValue’:
img4.c:752:43: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
         if (sizeof(uint64_t) == 8) printf("%llu",pnum);
                                           ^
img4.c: At top level:
img4.c:1012:97: warning: anonymous struct declared inside parameter list
 _cb(char elemNameStr[4], char *dgstData, size_t dgstDataLen, struct {plist_t rt
                                                                     ^
img4.c:1012:97: warning: its scope is only this definition or declaration, which is probably not what you want
img4.c: In function ‘verifyIMG4’:
img4.c:1254:2: warning: #warning TODO verify certificate chain [-Wcpp]
 #warning TODO verify certificate chain
  ^
mv -f .deps/img4tool-img4.Tpo .deps/img4tool-img4.Po
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -g -O2 -std=c11 -D IMG4TOOL_VERSION_COMMIT_COUNT=\"\" -D IMG4TOOL_VERSION_COMMIT_SHA=\"\" -MT img4tool-lzssdec.o -MD -MP -MF .deps/img4tool-lzssdec.Tpo -c -o img4tool-lzssdec.o `test -f 'lzssdec.c' || echo './'`lzssdec.c
lzssdec.c:35:21: error: unknown type name ‘u_int8_t’
 int decompress_lzss(u_int8_t *dst, u_int8_t *src, u_int32_t srclen){
                     ^
lzssdec.c:35:36: error: unknown type name ‘u_int8_t’
 int decompress_lzss(u_int8_t *dst, u_int8_t *src, u_int32_t srclen){
                                    ^
lzssdec.c:35:51: error: unknown type name ‘u_int32_t’
 int decompress_lzss(u_int8_t *dst, u_int8_t *src, u_int32_t srclen){
                                                   ^
lzssdec.c: In function ‘tryLZSS’:
lzssdec.c:89:28: warning: implicit declaration of function ‘ntohl’ [-Wimplicit-function-declaration]
     char *decomp = malloc (ntohl(compHeader->uncompressedSize));
                            ^
lzssdec.c:91:18: warning: implicit declaration of function ‘memmem’ [-Wimplicit-function-declaration]
     char *feed = memmem(compressed+64, 1024, sig, sizeof(sig));
                  ^
lzssdec.c:91:18: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
lzssdec.c:97:14: warning: implicit declaration of function ‘decompress_lzss’ [-Wimplicit-function-declaration]
     int rc = decompress_lzss((void*)decomp, (void*)feed, ntohl(compHeader->comp
              ^
Makefile:517: recipe for target 'img4tool-lzssdec.o' failed
make[2]: *** [img4tool-lzssdec.o] Error 1
make[2]: Leaving directory '/home/admin1/Downloads/img4tool-master/img4tool'
Makefile:397: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/admin1/Downloads/img4tool-master'
Makefile:329: recipe for target 'all' failed
make: *** [all] Error 2

This is the part when I use `./autogen.sh`

> libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/usr/share/aclocal/libtool.m4'
libtoolize:   '/usr/share/aclocal/ltoptions.m4'
libtoolize:   '/usr/share/aclocal/ltsugar.m4'
libtoolize:   '/usr/share/aclocal/ltversion.m4'
libtoolize:   '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:10: installing './compile'
configure.ac:11: installing './config.guess'
configure.ac:11: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
img4tool/Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libcrypto... yes
checking for compression_decode_buffer in -lcompression... no
checking for lzfse_decode_buffer in -llzfse... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for size_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for error_at_line... yes
checking for memmove... yes
checking for memset... yes
checking for libplist... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating img4tool/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Thanks for reading and sorry for bad english. I'm new to linux btw.

**Comment by kamakuba** [comment]
Just add `#include <sys/types.h>` in img4tool/lzssdec.h
it must look like
```
//
//  lzssdec.h
//  img4tool
//
//  Code borrowed from: http://newosxbook.com/src.jl?tree=listings&file=joker.c
//  Coded by Jonathan Levin (a.k.a @Morpheus______), http://newosxbook.com
#include <sys/types.h>

#ifndef lzssdec_h
#define lzssdec_h

#include <stdint.h>
#include <stdlib.h>

char *tryLZSS(char *compressed, size_t *filesize);

#endif /* lzssdec_h */
```
After that `make` finished without error.

**Comment by s0uthwest** [comment]
Fixed: https://github.com/tihmstar/img4tool/commit/c706ca81c39f7212a7e84d3770fe23b08381f654
