### ISSUE TITLE
fails to "make" Mojave

### ISSUE THREAD

**Issue by chriscrutt** [tihmstar/img4tool#14]
I receive:

Undefined symbols for architecture x86_64:
"_EVP_MD_CTX_create", referenced from:
_verify_signature in img4tool-img4.o
"_EVP_MD_CTX_destroy", referenced from:
_verify_signature in img4tool-img4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by s0uthwest** [comment]
Compile with OpenSSL.
