### ISSUE TITLE
libgeneral related error while compiling

### ISSUE THREAD

**Issue by EvilAirborn** [tihmstar/img4tool#16]
I have checked out the required submodule and successfully ran the autogen.sh without any error.
but after i start to make it with command ''make'' or ''sudo make'', both gives be following error:

make  all-recursive
make[1]: Entering directory '/home/mahin/img4tool'
Making all in img4tool
make[2]: Entering directory '/home/mahin/img4tool/img4tool'
Makefile:535: ../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo: No such file or directory
make[2]: *** No rule to make target '../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo'.  Stop.
make[2]: Leaving directory '/home/mahin/img4tool/img4tool'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mahin/img4tool'
Makefile:385: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by necbov** [comment]
use : git clone --recursive and git submodule update --recursive
that was the solution for me

**Comment by ElTifo** [comment]
Trying to complie on Catalina....
Configuration for img4tool-152:

At the end of ./autogen.sh:

-------------------------------------------

  install prefix ..........: /usr/local
  have plist ..............: yes
  crypto backend ..........: CommCrypto
  compiler ................: gcc

  Now type 'make' to build img4tool-152,
  and then 'make install' for installation.

WARNING: crypto_backend is not openssl, some features will be missing

When trying to run make:

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in img4tool
Makefile:534: ../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo: No such file or directory
make[2]: *** No rule to make target `../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Contents of /external/libgeneral folder:

eltifo@eltifos-Mac libgeneral % ls -la
total 16
drwxr-xr-x  4 eltifo  staff   128 Oct 28 16:38 .
drwxr-xr-x  6 eltifo  staff   192 Oct 28 16:38 ..
-rw-r--r--  1 eltifo  staff  1205 Oct 28 16:38 exception.cpp
-rw-r--r--  1 eltifo  staff   262 Oct 28 16:38 main.c

Something is wrong and I don't know what.

Already tried

git clone --recursive
git submodule update --recursive

**Comment by ElTifo** [comment]
Ok so I've finally compiled img4tool.

Decided to start from scratch and to move on to Mojave instead of Catalina.

Probably some dependencies where missing...

**Comment by Hacoga** [comment]
Hello @ElTifo, I get this error with:

`MX-IT02285:img4tool angel.trejo$ ./autogen.sh
./autogen.sh: line 3: aclocal: command not found
./autogen.sh: line 4: autoconf: command not found
./autogen.sh: line 5: autoheader: command not found
./autogen.sh: line 6: automake: command not found
./autogen.sh: line 7: autoreconf: command not found
./autogen.sh: line 8: ./configure: No such file or directory
`

 and previously the
```
 git clone --recursive
git submodule update --recursive. 
```

I have Mojave, 10.14.5.
Could you help me ? please.
Thank you!
