### ISSUE TITLE
multiple fatal errors after running make command

### ISSUE THREAD

**Issue by kid1carus** [tihmstar/img4tool#17]
./autogen.sh runs smoothly but when I type the make command I get 20 fatal errors and the process shuts down.  you can find a copy of my terminal output here:  https://pastebin.com/5S7wQeRm or in the attached text file
[Fatal Errors when building Img4Tool v2.txt](https://github.com/tihmstar/img4tool/files/3742527/Fatal.Errors.when.building.Img4Tool.v2.txt)

**Comment by necbov** [comment]
use : git clone --reclusive and git submodule update --recursive
that was the solution for me

**Comment by tihmstar** [comment]
Pastebin link invalid. If you have logs, you should paste them right here instead
