### ISSUE TITLE
fatal Error when issuing MAKE command

### ISSUE THREAD

**Issue by Saraseti** [tihmstar/img4tool#18]
./autogen.sh commmand runs smoothly but when I run the MAKE command thisnisnthe only error i get:

Making all in img4tool
g++ -DHAVE_CONFIG_H -I. -I..    -I../include -I../include/img4tool  -I/usr/local/Cellar/libplist/2.0.0_1/include   -g -O2 -std=c++11 -MT img4tool-main.o -MD -MP -MF .deps/img4tool-main.Tpo -c -o img4tool-main.o `test -f 'main.cpp' || echo './'`main.cpp
main.cpp:16:10: fatal error: 'img4tool/libgeneral/macros.h' file not found
#include <img4tool/libgeneral/macros.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [img4tool-main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Need a little assistance!

**Comment by necbov** [comment]
use : git clone --recursive and git submodule update --recursive
that was the solution for me

**Comment by Saraseti** [comment]
Thanks Bro, worked like a charm!!
