### ISSUE TITLE
Failed to find matching buildidentity

### ISSUE THREAD

**Issue by ethanjansen** [tihmstar/img4tool#19]
When trying to verify apticket it says:

> IM4M validation failed with error:
> [exception]:
> what=Failed to find matching buildidentity
> code=63373324
> line=967
> file=img4tool.cpp
> commit count=152
> APTicket is invalid!

APTicket was saved with tsschecker commit 288
and the latest commit of img4tool from @s0uthwest says that apticket is valid

**Comment by s0uthwest** [comment]
Give here your blob.

**Comment by ethanjansen** [comment]
@s0uthwest Here is an example:
[3769813057539366_iPhone9,2_d11ap_13.2-17B84_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2.zip](https://github.com/tihmstar/img4tool/files/3827797/3769813057539366_iPhone9.2_d11ap_13.2-17B84_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2.zip)

I only have this issue with iphone9,2 and there is actually another issue relating to RestoreRamDisk. I have no issues with an iphone8,1.

**Comment by ethanjansen** [comment]
Just checked again with the latest commit (d514ce5) and got the following errors with the same blob:

> img4tool version: 0.162-d514ce57f4a104aebe4ba8c20cd7c45f33cf3a68
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (found "aopf" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "Homer"                   OK (found "homr" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SE,Bootloader"           
failed verification with error:
[exception]:
what=assure failed
code=67371020
line=1028
file=img4tool.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 3:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 4:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 5:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (found "aopf" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "Homer"                   OK (found "homr" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SE,Bootloader"           
failed verification with error:
[exception]:
what=assure failed
code=67371020
line=1028
file=img4tool.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
[IMG4TOOL] checking buildidentity 6:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 7:
[IMG4TOOL] checking buildidentity matches board ... NO
>
> [IMG4TOOL] IM4M validation failed with error:
>
>[exception]:
what=Failed to find matching buildidentity
code=72744972
line=1110
file=img4tool.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
>
>[IMG4TOOL] APTicket is BAD!
[IMG4TOOL] SHSH2 contains generator 0x1111111111111111 which is GOOD for nonce in IM4M!

**Comment by s0uthwest** [comment]
Fixed in #25 pull request.
