### ISSUE TITLE
i can't download 

### ISSUE THREAD

**Issue by Romntic** [tihmstar/img4tool#24]
Hello how are ? 
![Screen Shot 2019-11-06 at 4 42 00 AM](https://user-images.githubusercontent.com/31198048/68261025-dbe73300-004f-11ea-951b-d119a8d2f9a9.png)
 do i need to pay for u or what ?

**Comment by 0x9fff00** [comment]
You have to run `./autogen.sh` first

**Comment by Romntic** [comment]
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$ ./autogen.sh
checking build system type... x86_64-apple-darwin17.7.0
checking host system type... x86_64-apple-darwin17.7.0
checking target system type... x86_64-apple-darwin17.7.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin17.7.0 file names to x86_64-apple-darwin17.7.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin17.7.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking whether we need platform-specific build settings... checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for openssl >= 0.9.8... no
checking for libplist >= 2.0.0... yes
checking for libgeneral >= 26... no
configure: error: Package requirements (libgeneral >= 26) were not met:

No package 'libgeneral' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libgeneral_CFLAGS
and libgeneral_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Romntic** [comment]
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by 0x9fff00** [comment]
> ```
> checking for libgeneral >= 26... no
> configure: error: Package requirements (libgeneral >= 26) were not met:
> 
> No package 'libgeneral' found
> ```

You need to install this. https://github.com/tihmstar/libgeneral

**Comment by Romntic** [comment]
i already install on this path 
MOHAMMEDs-Mac-mini-3:~ mmonahesh$ git clone https://github.com/tihmstar/libgeneral.git
Cloning into 'libgeneral'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 132 (delta 34), reused 128 (delta 30), pack-reused 0
Receiving objects: 100% (132/132), 17.97 KiB | 4.49 MiB/s, done.
Resolving deltas: 100% (34/34), done.
MOHAMMEDs-Mac-mini-3:~ mmonahesh$ cd libgeneral
MOHAMMEDs-Mac-mini-3:libgeneral mmonahesh$ ./autogen.sh
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:6: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:6: error: required file './ltmain.sh' not found
configure.ac:8: installing './missing'
libgeneral/Makefile.am: installing './depcomp'
aclocal: warning: couldn't open directory 'm4': No such file or directory
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
checking build system type... x86_64-apple-darwin17.7.0
checking host system type... x86_64-apple-darwin17.7.0
checking target system type... x86_64-apple-darwin17.7.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin17.7.0 file names to x86_64-apple-darwin17.7.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin17.7.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating libgeneral.pc
config.status: creating libgeneral/Makefile
config.status: creating config.h
config.status: executing libtool commands
config.status: executing depfiles commands

Configuration for libgeneral-26:
-------------------------------------------

  install prefix ..........: /usr/local
  compiler ................: gcc

  Now type 'make' to build libgeneral-26,
  and then 'make install' for installation.

MOHAMMEDs-Mac-mini-3:libgeneral mmonahesh$ make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/mmonahesh/libgeneral/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in libgeneral
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..    -I../include   -g -O2 -std=c++11 -MT libgeneral_la-exception.lo -MD -MP -MF .deps/libgeneral_la-exception.Tpo -c -o libgeneral_la-exception.lo `test -f 'exception.cpp' || echo './'`exception.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -g -O2 -std=c++11 -MT libgeneral_la-exception.lo -MD -MP -MF .deps/libgeneral_la-exception.Tpo -c exception.cpp  -fno-common -DPIC -o .libs/libgeneral_la-exception.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -g -O2 -std=c++11 -MT libgeneral_la-exception.lo -MD -MP -MF .deps/libgeneral_la-exception.Tpo -c exception.cpp -o libgeneral_la-exception.o >/dev/null 2>&1
mv -f .deps/libgeneral_la-exception.Tpo .deps/libgeneral_la-exception.Plo
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -I../include   -g -O2 -std=c++11   -o libgeneral.la -rpath /usr/local/lib libgeneral_la-exception.lo  
libtool: link: g++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libgeneral.0.dylib  .libs/libgeneral_la-exception.o    -g -O2   -install_name  /usr/local/lib/libgeneral.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
libtool: link: (cd ".libs" && rm -f "libgeneral.dylib" && ln -s "libgeneral.0.dylib" "libgeneral.dylib")
libtool: link: ar cru .libs/libgeneral.a  libgeneral_la-exception.o
libtool: link: ranlib .libs/libgeneral.a
libtool: link: ( cd ".libs" && rm -f "libgeneral.la" && ln -s "../libgeneral.la" "libgeneral.la" )
Making all in include
make[2]: Nothing to be done for `all'.
MOHAMMEDs-Mac-mini-3:libgeneral mmonahesh$ install
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

**Comment by Romntic** [comment]
but when in go to img4tool
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$ make
make: *** No targets specified and no makefile found.  Stop.
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$ git clone https://github.com/tihmstar/libgeneral.git
Cloning into 'libgeneral'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 132 (delta 34), reused 128 (delta 30), pack-reused 0
Receiving objects: 100% (132/132), 17.97 KiB | 4.49 MiB/s, done.
Resolving deltas: 100% (34/34), done.
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$ sudo make install
Password:
make: *** No rule to make target `install'.  Stop.
MOHAMMEDs-Mac-mini-3:img4tool mmonahesh$

**Comment by 0x9fff00** [comment]
You need to run all these three commands, first for libgeneral and then for img4tool:
```
./autogen.sh
make
sudo make install
```

**Comment by Romntic** [comment]
i'm great full for  u @0x9fff00 
it's complete install 

there is any tutorial for uses img4tool ?
