### ISSUE TITLE
Is lzfse still needed?

### ISSUE THREAD

**Issue by 0x9fff00** [tihmstar/img4tool#26]
Commit https://github.com/tihmstar/img4tool/commit/6aef7ad807f337c72ecb2063b63179ee4cd507cc#diff-67e997bcfdac55191033d57a16d1408aL46-L67 seems to have removed the dependency on lzfse from `configure.ac` (it hasn't been added back since then). Commit https://github.com/tihmstar/img4tool/commit/9599bc1258d9230ed725b70998653a4b85f0e089#diff-97483fb82a3a765bb568aaca4b04416cR19-R25 added some references to lzfse, but no actual use of lzfse functions. Was this added by mistake or does it still need lzfse?

**Comment by tihmstar** [comment]
Yes lzfse is still needed
