### ISSUE TITLE
Error at compile 

### ISSUE THREAD

**Issue by qiurigao** [tihmstar/img4tool#31]
img4tool.cpp: In function ‘void tihmstar::img4tool::printIMG4(const void*, size_t, bool, bool)’:
img4tool.cpp:312:30: ### error: ‘reverse’ is not a member of ‘std’
                         std::reverse(octetString.begin(), octetString.end());
                              ^~~~~~~

**Comment by elp0t0r1c0** [comment]
This is because `#include <algorithm>` is missing.
[This PR](https://github.com/tihmstar/img4tool/pull/32) should fix that.

**Comment by qiurigao** [comment]
main.cpp: In function ‘int main_r(int, const char**)’:
main.cpp:384:26: error: ‘reverse’ is not a member of ‘std’
                     std::reverse(octetString.begin(), octetString.end());
                          ^~~~~~~
main.cpp: In function ‘char* readFromFile(const char*, size_t*)’:
@elp0t0r1c0
