### ISSUE TITLE
Error at compile, recompile with -fPIC?

### ISSUE THREAD

**Issue by a878851497** [tihmstar/img4tool#34]
lsy@debian:~/ReRa1n/rerain-deps/img4tool$ make
make  all-recursive
make[1]: Entering directory '/home/lsy/ReRa1n/rerain-deps/img4tool'
Making all in img4tool
make[2]: Entering directory '/home/lsy/ReRa1n/rerain-deps/img4tool/img4tool'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -I../include -I../include/img4tool  -I/usr/local/include  -I/usr/local/include  -g -O2 -std=c++11 -L/usr/local/lib -lplist -lssl -lcrypto -L/usr/local/lib -lgeneral  -o libimg4tool.la -rpath /usr/local/lib libimg4tool_la-ASN1DERElement.lo libimg4tool_la-lzssdec.lo libimg4tool_la-img4tool.lo  -llzfse 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o  .libs/libimg4tool_la-ASN1DERElement.o .libs/libimg4tool_la-lzssdec.o .libs/libimg4tool_la-img4tool.o   -L/usr/local/lib /usr/local/lib/libplist.so -lssl -lcrypto /usr/local/lib/libgeneral.so -llzfse -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o  -g -O2   -pthread -Wl,-soname -Wl,libimg4tool.so.0 -o .libs/libimg4tool.so.0.0.0
/usr/bin/ld: /usr/local/lib/liblzfse.a(liblzfse_master.o): relocation R_X86_64_PC32 against symbol `lzfse_encode_scratch_size' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:463: recipe for target 'libimg4tool.la' failed
make[2]: *** [libimg4tool.la] Error 1
make[2]: Leaving directory '/home/lsy/ReRa1n/rerain-deps/img4tool/img4tool'
Makefile:481: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lsy/ReRa1n/rerain-deps/img4tool'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yy814819100** [comment]
me too

**Comment by tihmstar** [comment]
This issue isn't in img4tool, but in the way you compiled lzfse. 
To fix this you need to compile lzfse with -fPIC
