### ISSUE TITLE
Compress bvx2

### ISSUE THREAD

**Issue by ajsacco** [tihmstar/img4tool#35]
The ability to uncompress bvx2 was implemented in a commit about a month ago but the ability to re-compress them has not been implemented. Is this necessary?

**Comment by sitay1** [comment]
Any updates on that? currently trying to run ra1nsn0w on iPhone X 13.2.3/13.3 and it stuck with ("not implemented" error when trying to appendPayloadToIM4P.

**Comment by tihmstar** [comment]
So technically compressing bvx2 is supported as of the latest commit (e26f6e27c5fce7aff9e1ed5fe2b486b9989a5bec),
however i noticed that sending an custom compressed bvx2 payload makes the device not boot it for some reason.
I didn't get to debug that yet, however when sending the payload uncompressed it works
