### ISSUE TITLE
For anyone not being able to use the "--convert" flag

### ISSUE THREAD

**Issue by sha106b** [tihmstar/img4tool#37]
You most likely happen to have img4tool compiled without plist support, which is needed to use the convert option as described here in German: https://twitter.com/tihmstar/status/1210245489368666112

To fix this, either compile or install libplist via HomeBrew (brew install libplist), recompile img4tool and everything should work as intended!

**Comment by tihmstar** [comment]
Added info in f1fab496ce0a591c3d2b309e70e1f4ee9586d9e0
