### ISSUE TITLE
Can't Compile img4tool 

### ISSUE THREAD

**Issue by ScknCbt** [tihmstar/img4tool#41]
MacBookPro:~ User$ cd Downloads/img4tool-master/
MacBookPro:img4tool-master User$ ./autogen.sh 
aclocal: warning: couldn't open directory 'm4': No such file or directory
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
configure.ac:8: error: AC_INIT should be called with package and version arguments
/usr/local/Cellar/automake/1.16.1_1/share/aclocal-1.16/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
configure.ac:8: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
configure.ac:6: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:10: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
img4tool/Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
img4tool/Makefile.am:5:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
img4tool/Makefile.am:5:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
img4tool/Makefile.am:5:   If 'LT_INIT' is in 'configure.ac', make sure
img4tool/Makefile.am:5:   its definition is in aclocal's search path.
img4tool/Makefile.am: installing './depcomp'
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
aclocal: warning: couldn't open directory 'm4': No such file or directory
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
configure.ac:8: error: AC_INIT should be called with package and version arguments
/usr/local/Cellar/automake/1.16.1_1/share/aclocal-1.16/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
configure.ac:8: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by sadponyguerillaboy** [comment]
> MacBookPro:~ User$ cd Downloads/img4tool-master/
> MacBookPro:img4tool-master User$ ./autogen.sh
> aclocal: warning: couldn't open directory 'm4': No such file or directory
> fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
> configure.ac:8: error: AC_INIT should be called with package and version arguments
> /usr/local/Cellar/automake/1.16.1_1/share/aclocal-1.16/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
> configure.ac:8: the top level
> autom4te: /usr/bin/m4 failed with exit status: 1
> aclocal: error: echo failed with exit status: 1
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> configure.ac:6: error: possibly undefined macro: AM_PROG_LIBTOOL
> If this token and others are legitimate, please use m4_pattern_allow.
> See the Autoconf documentation.
> configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
> configure.ac:10: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
> configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
> configure.ac: that aclocal.m4 is present in the top-level directory,
> configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
> configure.ac:4: installing './config.guess'
> configure.ac:4: installing './config.sub'
> img4tool/Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
> img4tool/Makefile.am:5: The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> img4tool/Makefile.am:5: to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> img4tool/Makefile.am:5: If 'LT_INIT' is in 'configure.ac', make sure
> img4tool/Makefile.am:5: its definition is in aclocal's search path.
> img4tool/Makefile.am: installing './depcomp'
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: to 'configure.ac' and run 'aclocal' and 'autoconf' again
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: The usual way to define 'AMDEP' is to add one of the compiler tests
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: to 'configure.ac' and run 'aclocal' and 'autoconf' again
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/am/depend2.am: to 'configure.ac' and run 'aclocal' and 'autoconf' again
> aclocal: warning: couldn't open directory 'm4': No such file or directory
> fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
> configure.ac:8: error: AC_INIT should be called with package and version arguments
> /usr/local/Cellar/automake/1.16.1_1/share/aclocal-1.16/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
> configure.ac:8: the top level
> autom4te: /usr/bin/m4 failed with exit status: 1
> aclocal: error: echo failed with exit status: 1
> autoreconf: aclocal failed with exit status: 1
> configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

It looks like you are missing some dependencies. A full run through if starting from scratch would look like:

Open terminal:

Install Brew (if not already installed)
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`

Then install dependencies:
`brew install m4`
`brew install libtool`
`brew install automake`
`brew install make`

Then Start Building From Source:
`sudo mkdir source`
`cd source`
`sudo git clone https://github.com/tihmstar/libgeneral`
`cd libgeneral`
`sudo ./autogen.sh`
`sudo make`
`sudo make install`
`cd ..`
`sudo git clone https://github.com/tihmstar/img4tool`
`cd img4tool`
`git submodule init`
`git submodule update`
`sudo ./autogen.sh`
`sudo make`
`sudo make install`

That should cover it. Mix and match depending on your setup.
