### ISSUE TITLE
Mac OS High Sierra

### ISSUE THREAD

**Issue by thoma599** [tihmstar/img4tool#43]
is there a fix I can do for this? 10.13

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/******/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/*******/Downloads/PyBoot-master/./resources/bin/img4tool

**Comment by 0n1cOn3** [comment]
Currently only supported for macOS Catalina (10.15)
