### ISSUE TITLE
autogen.sh doesn't recognize libplist installed

### ISSUE THREAD

**Issue by albyvar25** [tihmstar/img4tool#44]
Libplist is installed with macports, brew and via build, but autogen.sh is not finding it 
Configuration for img4tool-182:
-------------------------------------------

  install prefix ..........: /usr/local
  have plist ..............: no
  crypto backend ..........: CommCrypto
  compiler ................: gcc

  Now type 'make' to build img4tool-182,
  and then 'make install' for installation.

**Comment by 0x9fff00** [comment]
I've created a pull request to fix this (#45).
