### ISSUE TITLE
./configure: line 16573: syntax error near unexpected token `openssl,'

### ISSUE THREAD

**Issue by hipp013** [tihmstar/img4tool#46]
I am trying to run `autogen.sh` but keep running into the same error:

```
checking whether we need platform-specific build settings... ./configure: line 16573: syntax error near unexpected token `openssl,'
./configure: line 16573: `PKG_CHECK_MODULES(openssl, $OPENSSL_REQUIRES_STR, have_openssl=yes, have_openssl=no)
```

I have OpenSSL installed via `brew`. I've tried deleting and recloning the git and everything I can think of, but no luck. Please get back to me soon and let me know if I'm doing something wrong. 

edit: On macOS High Sierra 10.13.4

**Comment by tihmstar** [comment]
Looks like you don't have pkg-config installed

**Comment by hipp013** [comment]
Yes I do, I have `pkg-config 0.29.2_3` installed. Is there an issue with where `./configure` is looking for dependencies?

I also talked with someone on Discord who gave me this chunk of code to run, which still didn't work:
```
LD_LIBRARY_PATH=/usr/local/opt/openssl/lib:"${LD_LIBRARY_PATH}"                    
CPATH=/usr/local/opt/openssl/include:"${CPATH}"                                    
PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:"${PKG_CONFIG_PATH}"          
export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH     
```

**Comment by hipp013** [comment]
I ended up installing stek29's homebrew-idevice and running `brew install img4tool`, which fixed the issue. I'm still wondering why this error kept popping up though, because I thought I had everything configured correctly.
