### ISSUE TITLE
the lattest commitment can not be built

### ISSUE THREAD

**Issue by maenpaa24** [tihmstar/img4tool#7]
Hi!

Until the last commitment I could build any img4tool version with autotools (basically autogen.sh, make, make isntall). However, when I try to build the latest version it comes up with the following error related to linked libraries (which seems to have something to do with the new lzss library):

gcc -I/path/include -I/path//include -g -O2 -std=c11 -o img4tool img4tool-img4tool.o img4tool-img4.o  -L/path/lib -L/path/lib /path/lib/libplist.dylib -lcrypto
Undefined symbols for architecture x86_64:
  "_tryLZSS", referenced from:
      _extractFileFromIM4P in img4tool-img4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [img4tool] Error 1

Thank you beforehand. I hope to hear from you soon.

By the way: I am using mac os sierra 10.12.6. Please ask if you need any further information.

**Comment by tihmstar** [comment]
Can you check latest commit?
I remember seeing and fixing this issue

**Comment by maenpaa24** [comment]
Sure! Yes it now works!! Thank you very much!
